config/routes.rb
Textbook::Application.routes.draw do
  resources :books
  get 'search' => 'books#search'
  get 'library/:id' => "books#library"

  get 'destroy_notifications' => "notifications#destroy_all"

  resources :messages

   root 'books#search'

   get 'users/:id/edit' => "users#edit", :as => "edit_user"
   post 'users/:id/edit' => "users#update", :as => "user"
   patch 'users/:id/edit' => "users#update"

end

app/models/message.rb
class Message < ActiveRecord::Base
	belongs_to :sender, :class_name => "User"
	belongs_to :receiver, :class_name => "User"
	has_one :notification

	after_create :create_notification

	def create_notification
		Notification.create(:user_id => receiver.id, :message_id => self.id)
		if receiver.email_notification
			begin
				MessageMailer.new_message_notification(self).deliver
			rescue Exception
			end
		end
	end

	def preview
		self.text.truncate(30)
	end

	def other_user(user)
		user == sender ? receiver : sender
	end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_message, only: [:show, :edit, :update, :destroy]

  # GET /messages
  # GET /messages.json
  def index
    @conversations = current_user.conversations
  end

  # GET /messages/1
  # GET /messages/1.json
  def show
  end

  # GET /messages/new
  def new
    @receiver = User.find(params[:receiver_id])
    @message = current_user.sent_messages.build(:receiver_id => @receiver.id)
    @conversation = current_user.conversation(@receiver.id)
    book = params[:book_id] ? Book.find(params[:book_id]) : nil
    @preview = book ? "I want to buy your #{book.course} book!" : ""
    notifications = current_user.notifications_with(@receiver.id)
    notifications.each {|n| n.destroy }
  end

  # GET /messages/1/edit
  def edit
  end

  # POST /messages
  # POST /messages.json
  def create
    @message = current_user.sent_messages.build(message_params)

    respond_to do |format|
      if @message.save
        format.html { redirect_to new_message_path(:receiver_id => @message.receiver_id) }
        format.json { render action: 'show', status: :created, location: @message }
      else
        format.html { render action: 'new' }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /messages/1
  # PATCH/PUT /messages/1.json
  def update
    respond_to do |format|
      if @message.update(message_params)
        format.html { redirect_to @message, notice: 'Message was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /messages/1
  # DELETE /messages/1.json
  def destroy
    @message.destroy
    respond_to do |format|
      format.html { redirect_to messages_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_message
      @message = Message.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def message_params
      params.require(:message).permit(:sender_id, :receiver_id, :text, :book_id)
    end
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/messages/_conversation.html.haml
- @conversation.each do |message|
  - if message.sender == current_user
    .sent
      %div{:style => "border-bottom: 1px solid #e0e0dc;"}
  - else
    .received{:style => "color:white;"}
      %div{:style => "border-bottom: 1px solid #2a333c; color:white;"}
  = message.sender.email
  %div{:style => "float:right;text-align:right;"}
    = message.created_at.localtime.strftime('%b %e, %l:%M %p')
  %br/
  = message.text
.clearfix
%hr{:style => "border-top:1px solid gray;"}/

app/views/messages/_form.html.haml
= form_for @message, :html => { :class => 'form-horizontal' } do |f|
  = f.hidden_field :receiver_id, :class => 'text_field'
  = f.text_area :text, :class => 'text_field sent', :placeholder => "New Message", :value => @preview
  .clearfix
  %br/
  %div{:style => "text-align:right; "}
    = f.submit "Send Message", :class => 'btn btn-primary'
    = link_to "Cancel", messages_path, :class => 'btn'

app/views/messages/edit.html.haml
- model_class = Message
.page-header
  %h1= t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize
= render :partial => 'form'

app/views/messages/index.html.haml
- model_class = Message
.page-header
  %h1 Conversations
- if @conversations.length > 0
  %table.table.table-striped
    %thead
      %tr
        %th
        %th Last Message
        %th From
        %th To
        %th Preview
    %tbody
      - @conversations.each do |message|
        %tr.linkify{:onclick => "window.location.href = '#{new_message_path(message, :receiver_id => message.other_user(current_user).id)}';"}
          %td
            - notifs = current_user.notifications_with(message.other_user(current_user))
            %span.badge.badge-important= notifs.count unless notifs.count == 0
          %td= message.created_at.localtime.strftime('%b %e, %l:%M %p')
          %td= message.sender.email
          %td= message.receiver.email
          %td= message.preview
- else
  .alert.alert-block.text-center
    You haven't sent or received any messages.

app/views/messages/new.html.haml
:javascript
  location.href = "#bottom";
- model_class = Message
.page-header
  %h3
    Conversation with #{@receiver.email}
.block
  .centered
    = render :partial => 'conversation' if !@conversation.blank?
    = render :partial => 'form'
%span#bottom

app/views/messages/show.html.haml
- model_class = Message
.page-header
  %h1= t '.title', :default => model_class.model_name.human.titleize
%dl.dl-horizontal
  %dt
    %strong
      = model_class.human_attribute_name(:sender_id)
      \:
  %dd= @message.sender_id
  %dt
    %strong
      = model_class.human_attribute_name(:receiver_id)
      \:
  %dd= @message.receiver_id
  %dt
    %strong
      = model_class.human_attribute_name(:text)
      \:
  %dd= @message.text
.form-actions
  = link_to t('.back', :default => t("helpers.links.back")), |
    messages_path, :class => 'btn'                           |