config/routes.rb
Textbook::Application.routes.draw do
  resources :books
  get 'search' => 'books#search'
  get 'library/:id' => "books#library"

  get 'destroy_notifications' => "notifications#destroy_all"

  resources :messages

   root 'books#search'

   get 'users/:id/edit' => "users#edit", :as => "edit_user"
   post 'users/:id/edit' => "users#update", :as => "user"
   patch 'users/:id/edit' => "users#update"

end

app/models/notification.rb
class Notification < ActiveRecord::Base
	belongs_to :user
	belongs_to :message
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  before_action :set_notification, only: [:show, :edit, :update, :destroy]

  # GET /notifications
  # GET /notifications.json
  def index
    @notifications = Notification.all
  end

  # GET /notifications/1
  # GET /notifications/1.json
  def show
  end

  # GET /notifications/new
  def new
    @notification = Notification.new
  end

  # GET /notifications/1/edit
  def edit
  end

  # POST /notifications
  # POST /notifications.json
  def create
    @notification = Notification.new(notification_params)

    respond_to do |format|
      if @notification.save
        format.html { redirect_to @notification, notice: 'Notification was successfully created.' }
        format.json { render action: 'show', status: :created, location: @notification }
      else
        format.html { render action: 'new' }
        format.json { render json: @notification.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /notifications/1
  # PATCH/PUT /notifications/1.json
  def update
    respond_to do |format|
      if @notification.update(notification_params)
        format.html { redirect_to @notification, notice: 'Notification was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @notification.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notifications/1
  # DELETE /notifications/1.json
  def destroy
    @notification.destroy
    respond_to do |format|
      format.html { redirect_to notifications_url }
      format.json { head :no_content }
    end
  end

  def destroy_all
    current_user.notifications.destroy_all
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_notification
      @notification = Notification.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def notification_params
      params.require(:notification).permit(:user_id, :message_id)
    end
end

app/helpers/notifications_helper.rb
module NotificationsHelper
end

app/views/notifications/_form.html.haml
= form_for @notification, :html => { :class => 'form-horizontal' } do |f|
  .control-group
    = f.label :user_id, :class => 'control-label'
    .controls
      = f.text_field :user_id, :class => 'text_field'
  .control-group
    = f.label :message_id, :class => 'control-label'
    .controls
      = f.text_field :message_id, :class => 'text_field'
  .form-actions
    = f.submit nil, :class => 'btn btn-primary'
    = link_to t('.cancel', :default => t("helpers.links.cancel")), |
      notifications_path, :class => 'btn'                          |

app/views/notifications/edit.html.haml
- model_class = Notification
.page-header
  %h1= t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize
= render :partial => 'form'

app/views/notifications/index.html.haml
- model_class = Notification
.page-header
  %h1= t '.title', :default => model_class.model_name.human.pluralize.titleize
%table.table.table-striped
  %thead
    %tr
      %th= model_class.human_attribute_name(:id)
      %th= model_class.human_attribute_name(:user_id)
      %th= model_class.human_attribute_name(:message_id)
      %th= model_class.human_attribute_name(:created_at)
      %th= t '.actions', :default => t("helpers.actions")
  %tbody
    - @notifications.each do |notification|
      %tr
        %td= link_to notification.id, notification_path(notification)
        %td= notification.user_id
        %td= notification.message_id
        %td= l notification.created_at
        %td
          = link_to t('.edit', :default => t("helpers.links.edit")),       |
            edit_notification_path(notification), :class => 'btn btn-mini' |
          -#
          = link_to t('.destroy', :default => t("helpers.links.destroy")),                                               |
            notification_path(notification),                                                                             |
            :method => :delete,                                                                                          |
            :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, |
            :class => 'btn btn-mini btn-danger'                                                                          |
= link_to t('.new', :default => t("helpers.links.new")), |
  new_notification_path,                                 |
  :class => 'btn btn-primary'                            |

app/views/notifications/new.html.haml
- model_class = Notification
.page-header
  %h1= t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize
= render :partial => 'form'

app/views/notifications/show.html.haml
- model_class = Notification
.page-header
  %h1= t '.title', :default => model_class.model_name.human.titleize
%dl.dl-horizontal
  %dt
    %strong
      = model_class.human_attribute_name(:user_id)
      \:
  %dd= @notification.user_id
  %dt
    %strong
      = model_class.human_attribute_name(:message_id)
      \:
  %dd= @notification.message_id
.form-actions
  = link_to t('.back', :default => t("helpers.links.back")), |
    notifications_path, :class => 'btn'                      |
  -#
  = link_to t('.edit', :default => t("helpers.links.edit")), |
    edit_notification_path(@notification), :class => 'btn'   |
  -#
  = link_to t('.destroy', :default => t("helpers.links.destroy")),                                               |
    notification_path(@notification),                                                                            |
    :method => 'delete',                                                                                         |
    :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, |
    :class => 'btn btn-danger'                                                                                   |