config/routes.rb
Textbook::Application.routes.draw do
  resources :books
  get 'search' => 'books#search'
  get 'library/:id' => "books#library"

  get 'destroy_notifications' => "notifications#destroy_all"

  resources :messages

   root 'books#search'

   get 'users/:id/edit' => "users#edit", :as => "edit_user"
   post 'users/:id/edit' => "users#update", :as => "user"
   patch 'users/:id/edit' => "users#update"

end

app/models/book.rb
require_relative 'amazon_book_scraper'

class Book < ActiveRecord::Base
	belongs_to :user
	after_create :scrape_amazon

	DEPARTMENTS = [
		"ACCT",
		"ACES",
		"ADHT",
		"ADVC",
		"AIOM",
		"AMST",
		"ANAT",
		"ANES",
		"ANTH",
		"APMU",
		"ARAB",
		"ARSC",
		"ARTH",
		"ARTK",
		"ARTS",
		"ASCV",
		"ASIA",
		"ASTR",
		"BAFI",
		"BASC",
		"BETH",
		"BIOC",
		"BIOL",
		"BIOM",
		"BIOS",
		"BLAW",
		"BSTP",
		"CARD",
		"CBIO",
		"CFNU",
		"CHEM",
		"CHIN",
		"CHST",
		"CIAR",
		"CLBY",
		"CLIN",
		"CLMI",
		"CLSC",
		"CMED",
		"CMPL",
		"CMPS",
		"CNCR",
		"COGS",
		"COLS",
		"COMP",
		"COOP",
		"COPE",
		"CORE",
		"COSI",
		"CRSP",
		"DANC",
		"DART",
		"DENC",
		"DEND",
		"DENF",
		"DENT",
		"DERM",
		"DGMS",
		"DMLL",
		"DNDO",
		"DPED",
		"DPER",
		"DPHC",
		"DRTH",
		"DSPR",
		"DSRE",
		"EBME",
		"ECHE",
		"ECIV",
		"ECMP",
		"ECON",
		"EDJC",
		"EDMP",
		"EDUC",
		"EEAP",
		"EECS",
		"EEPS",
		"EFDA",
		"EFTS",
		"EIND",
		"EMAC",
		"EMAE",
		"EMBA",
		"EMCH",
		"EMMD",
		"EMMS",
		"EMSE",
		"ENDO",
		"ENG",
		"ENGD",
		"ENGL",
		"ENGR",
		"ENTP",
		"EPBI",
		"EPOM",
		"ERAS",
		"ERTH",
		"ESAD",
		"ESCI",
		"ESMD",
		"ESTD",
		"ESYS",
		"ETHC",
		"ETHS",
		"EVHS",
		"EXAM",
		"EXCH",
		"FAMD",
		"FRCH",
		"FRSS",
		"FSCC",
		"FSCS",
		"FSNA",
		"FSSO",
		"FSSY",
		"FSTS",
		"FUND",
		"GAST",
		"GENE",
		"GEOG",
		"GEOL",
		"GERI",
		"GERM",
		"GERO",
		"GMBA",
		"GRAD",
		"GREK",
		"GRMN",
		"GTOX",
		"HBRW",
		"HDEV",
		"HEAL",
		"HEMA",
		"HEWB",
		"HLTH",
		"HSED",
		"HSMC",
		"HSST",
		"HSTY",
		"HUMN",
		"HWDP",
		"IBIS",
		"IBMS",
		"IDHS",
		"IDRL",
		"IECS",
		"IIME",
		"IMED",
		"IMMU",
		"INCA",
		"INQU",
		"INTH",
		"INTL",
		"IPOD",
		"ITAL",
		"ITAM",
		"JAPN",
		"JDST",
		"JRAB",
		"LAPP",
		"LATN",
		"LAWS",
		"LCAN",
		"LDRS",
		"LHRP",
		"LIBS",
		"LING",
		"LINS",
		"LITR",
		"LLM",
		"LMON",
		"LSAB",
		"LYON",
		"MAHE",
		"MANC",
		"MAND",
		"MATH",
		"MBAC",
		"MBAP",
		"MBIO",
		"MEDS",
		"MEDT",
		"MGAB",
		"MGMT",
		"MIDS",
		"MILT",
		"MISC",
		"MKMR",
		"MLIT",
		"MLSC",
		"MMED",
		"MONT",
		"MPHP",
		"MPOD",
		"MRKM",
		"MSFC",
		"MSFI",
		"MSOR",
		"MSPL",
		"MSTP",
		"MUAP",
		"MUAR",
		"MUCP",
		"MUDE",
		"MUED",
		"MUEN",
		"MUGN",
		"MUHI",
		"MULI",
		"MUPD",
		"MUPM",
		"MURP",
		"MUSC",
		"MUSD",
		"MUTH",
		"MVIR",
		"NEUM",
		"NEUR",
		"NEUS",
		"NORG",
		"NTRN",
		"NUAN",
		"NUED",
		"NUND",
		"NUNI",
		"NUNP",
		"NURS",
		"OBGY",
		"OPMT",
		"OPRE",
		"OPTH",
		"ORBH",
		"ORTH",
		"OTHR",
		"OTOL",
		"PATH",
		"PEDS",
		"PHED",
		"PHIL",
		"PHOL",
		"PHRM",
		"PHYS",
		"PLCY",
		"PORT",
		"POSC",
		"PRAC",
		"PSCL",
		"PSYC",
		"PSYY",
		"PULM",
		"QUMM",
		"RADI",
		"RBIO",
		"READ",
		"REHA",
		"REHE",
		"REMA",
		"RENL",
		"RESC",
		"RHEU",
		"RLGN",
		"RSCH",
		"RUSN",
		"SASS",
		"SIDS",
		"SJUS",
		"SMAB",
		"SOCI",
		"SPAN",
		"SPCH",
		"SPPP",
		"SRAB",
		"SRCH",
		"SSBT",
		"SSCI",
		"SSWM",
		"STAT",
		"SURG",
		"SWBC",
		"SYBB",
		"SYPS",
		"TELA",
		"THTR",
		"UCAP",
		"UGSP",
		"UNEL",
		"UNIV",
		"URES",
		"UROL",
		"USEM",
		"USFS",
		"USNA",
		"USSO",
		"USSY",
		"VACA",
		"WASH",
		"WGST",
		"WHUK",
		"WIEN",
		"WLIT",
		"WMST",
		"WSTD"
	]

	CONDITIONS = [
		"New",
		"Used - Like New",
		"Used - Very Good",
		"Used - Good",
		"Used - Acceptable",
		"Used - Poor"
	]


	def preview
		title.truncate(30)
	end

	def course
		"#{dept} #{course_num}"
	end

	private

	def scrape_amazon
		return if amazon_url.blank?
		
		url = amazon_url.gsub(/ref=.*/, "")

		book = AmazonBookScraper::scrape(url)

		self.update_attributes(
				:title => book[:title],
				:publisher => book[:publisher],
				:edition => book[:edition],
				:author => book[:author],
				:isbn_10 => book[:isbn_10],
				:isbn_13 => book[:isbn_13],
				:img_url => book[:img_url]
			)
	end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy]

  def search
    @books = Book.order(dept: :asc, course_num: :asc)

    respond_to do |format|
      format.html
      format.json {render json: BooksDatatable.new(view_context)}
    end
  end

  # GET /books
  # GET /books.json
  def index
    @books = current_user.books
  end

  def library
    @user = User.find(params[:id])
    @books = @user.books
  end

  # GET /books/1
  # GET /books/1.json
  def show
  end

  # GET /books/new
  def new
    @book = current_user.books.build
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books
  # POST /books.json
  def create
    @book = current_user.books.build(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to @book }
        format.json { render action: 'show', status: :created, location: @book }
      else
        format.html { render action: 'new' }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1
  # PATCH/PUT /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to @book, notice: 'Book was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to books_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def book_params
      params.require(:book).permit(:title, :price, :dept, :course_num, :amazon_url, :isbn_10, :isbn_13, :author, :publisher, :edition, :user_id, :notes, :condition)
    end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_form.html.haml
:javascript
  $(document).ready( function() {
    $('#book_amazon_url').popover({'placement': 'right', 'trigger': 'manual'});
    $('#book_amazon_url').popover('show');

    $('#book_amazon_url').focus( function () {
      $('#book_amazon_url').popover('destroy');
    });
  });
= form_for @book, :html => { :class => 'form-horizontal' } do |f|
  .control-group
    = f.label :amazon_url, :class => 'control-label'
    .controls
      = f.text_field :amazon_url, :placeholder => "http://www.amazon.com/...", :class => 'text_field', :"data-toggle"=>"tooltip", :title=>"",  :"data-original-title"=>"Why do I need this?", :"data-content" => "Information about the textbook will be scraped from Amazon. If there are errors in the scraping, you will be able to edit it afterwards."
  .control-group
    = f.label :dept, "Course", :class => 'control-label'
    .controls
      = f.select :dept, Book::DEPARTMENTS, {}, :style => "width:101px;"
      = f.text_field :course_num, :placeholder => "101", :style => "width:101px;", :class => 'text_field'
  .control-group
    = f.label :condition, :class => 'control-label'
    .controls
      = f.select :condition, Book::CONDITIONS
  .control-group
    = f.label :price, "Asking Price", :class => 'control-label'
    .controls
      = f.text_field :price, :placeholder => "100.00", :class => 'text_field'
  .control-group
    = f.label :notes, "Comments", :class => 'control-label'
    .controls
      = f.text_area :notes, :class => 'text_field'
  .form-actions
    = f.submit "Add Book", :class => 'btn btn-primary'
    = link_to t('.cancel', :default => t("helpers.links.cancel")), |
      books_path, :class => 'btn'                                  |

app/views/books/_full_form.html.haml
= form_for @book, :html => { :class => 'form-horizontal' } do |f|
  .control-group
    = f.label :title, :class => 'control-label'
    .controls
      = f.text_field :title, :class => 'text_field'
  .control-group
    = f.label :author, :class => 'control-label'
    .controls
      = f.text_field :author, :class => 'text_field'
  .control-group
    = f.label :edition, :class => 'control-label'
    .controls
      = f.text_field :edition, :class => 'text_field'
  .control-group
    = f.label :publisher, :class => 'control-label'
    .controls
      = f.text_field :publisher, :class => 'text_field'
  .control-group
    = f.label :dept, "Course", :class => 'control-label'
    .controls
      = f.select :dept, Book::DEPARTMENTS, {}, :style => "width:101px;"
      = f.text_field :course_num, :placeholder => "101", :style => "width:101px;", :class => 'text_field'
  .control-group
    = f.label :condition, :class => 'control-label'
    .controls
      = f.select :condition, Book::CONDITIONS
  .control-group
    = f.label :price, "Asking Price", :class => 'control-label'
    .controls
      = f.text_field :price, :placeholder => "100.00", :class => 'text_field'
  .control-group
    = f.label :amazon_url, :class => 'control-label'
    .controls
      = f.text_field :amazon_url, :placeholder => "http://www.amazon.com/...", :class => 'text_field'
  .control-group
    = f.label :notes, "Comments", :class => 'control-label'
    .controls
      = f.text_area :notes, :class => 'text_field'
  .form-actions
    = f.submit "Add Book", :class => 'btn btn-primary'
    = link_to t('.cancel', :default => t("helpers.links.cancel")), |
      books_path, :class => 'btn'                                  |

app/views/books/edit.html.haml
- model_class = Book
.page-header
  %h1= t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize
= render :partial => 'full_form'

app/views/books/index.html.haml
- model_class = Book
.page-header
  %h1 My Library
- if @books.length > 0
  %table.table.table-striped.display.thumbnail
    %thead
      %tr
        %th Cover
        %th= model_class.human_attribute_name(:title)
        %th= model_class.human_attribute_name(:dept)
        %th= model_class.human_attribute_name(:course_num)
        %th= model_class.human_attribute_name(:condition)
        %th= model_class.human_attribute_name(:price)
        %th= t '.actions', :default => t("helpers.actions")
    %tbody
      - @books.each do |book|
        %tr
          %td= raw book.img_url.blank? ? "" : "<img src='#{book.img_url}'>"
          %td= link_to(book.title, book)
          %td= book.dept
          %td= book.course_num
          %td= book.condition
          %td= number_to_currency(book.price)
          %td
            = link_to t('.edit', :default => t("helpers.links.edit")), |
              edit_book_path(book), :class => 'btn btn-mini'           |
            -#
            = link_to t('.destroy', :default => t("helpers.links.destroy")),                                               |
              book_path(book),                                                                                             |
              :method => :delete,                                                                                          |
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, |
              :class => 'btn btn-mini btn-danger'                                                                          |
- else
  .alert.alert-block.text-center
    You have no books in your library! Click "Add Book to Library" to start selling.
%br/
= link_to "Add Book to Library", |
  new_book_path,                 |
  :class => 'btn btn-primary'    |

app/views/books/library.html.haml
- model_class = Book
.page-header
  %h1
    = @user.email
    's Library
%table.table.table-striped.display.thumbnail
  %thead
    %tr
      %th Cover
      %th= model_class.human_attribute_name(:title)
      %th= model_class.human_attribute_name(:dept)
      %th= model_class.human_attribute_name(:course_num)
      %th= model_class.human_attribute_name(:condition)
      %th= model_class.human_attribute_name(:price)
  %tbody
    - @books.each do |book|
      %tr
        %td= raw book.img_url.blank? ? "" : "<img src='#{book.img_url}'>"
        %td= link_to(book.title, book)
        %td= book.dept
        %td= book.course_num
        %td= book.condition
        %td= book.price
%br/
= link_to "Back to Search", search_path, :class=>"btn"

app/views/books/new.html.haml
.page-header
  %h1 Add Book to Library
= render :partial => 'form'

app/views/books/search.html.haml
- model_class = Book
.page-header
  %h1 Find Books
%table#books.table.table-striped.display.thumbnail{"data-source" => search_url(format: "json")}
  %thead
    %tr
      %th Cover
      %th= model_class.human_attribute_name(:title)
      %th= model_class.human_attribute_name(:dept)
      %th= model_class.human_attribute_name(:course_num)
      %th= model_class.human_attribute_name(:condition)
      %th= model_class.human_attribute_name(:price)
  %tbody
    - @books.each do |book|
      %tr
        %td= raw book.img_url.blank? ? "" : "<img src='#{book.img_url}'>"
        %td= link_to(book.title, book)
        %td= book.dept
        %td= book.course_num
        %td= book.condition
        %td= book.price

app/views/books/show.html.haml
- model_class = Book
.page-header
  %h1 Book Info
- if @book.user == current_user
  .alert.alert-notice.text-center
    Incorrectly scraped information? Click "Edit Info" to update it manually.
%table{:style => "text-align:top;"}
  %colgroup
    %col{:span => "1", :style => "width: 30%;"}/
    %col{:span => "1", :style => "width: 70%;"}/
  %tr
    %td
      = link_to @book.amazon_url do
        %img{:src => @book.img_url}/
    %td{:valign => "top"}
      .span6
        %p.lead
          %strong= @book.title
        %ul.media-list
          %li
            %strong Author:
            = @book.author
          %li
            %strong Edition:
            = @book.edition
          %li
            %strong Publisher:
            = @book.publisher
          %li
            %strong ISBN-10:
            = @book.isbn_10
          %li
            %strong ISBN-13:
            = @book.isbn_13
          %li
            %strong Sold By:
            = @book.user.email
          %li
            %strong Course:
            = @book.dept
            = @book.course_num
          %li
            %strong Condition:
            = @book.condition
          %li
            %strong Asking Price:
            = number_to_currency(@book.price)
          %li
            %strong Notes:
            = @book.notes
.form-actions
  - if @book.user == current_user
    = link_to "Add Another Book", new_book_path, :class => 'btn btn'
    = link_to "Back to Library", books_path, :class => 'btn'
    = link_to "Edit Info", edit_book_path(@book), :class => 'btn'
    = link_to "Delete", book_path(@book), :method => 'delete', :confirm => 'Are you sure?', :class => 'btn btn-danger'
  - else
    .alert.alert-block.alert-error
      %h4 Note:
      This site does not handle payment. Message the owner to agree on transaction details.
    = link_to "Back", search_path, :class => "btn"
    = link_to("Owner's Other Books", {:controller => "books", :action => "library", :id => @book.user_id}, {:class => 'btn btn-success'})
    = link_to "Send Message to Owner", new_message_path(:receiver_id => @book.user_id, :book_id => @book.id), :class => "btn btn-primary"