config/routes.rb
Textbook::Application.routes.draw do
  resources :books
  get 'search' => 'books#search'
  get 'library/:id' => "books#library"

  get 'destroy_notifications' => "notifications#destroy_all"

  resources :messages

   root 'books#search'

   get 'users/:id/edit' => "users#edit", :as => "edit_user"
   post 'users/:id/edit' => "users#update", :as => "user"
   patch 'users/:id/edit' => "users#update"

end

app/views/layouts/application.html.haml
!!!
%html{:lang => "en"}
  %head
    %meta{:charset => "utf-8"}/
    %meta{:content => "IE=Edge,chrome=1", "http-equiv" => "X-UA-Compatible"}/
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}/
    %link{:href => "//netdna.bootstrapcdn.com/font-awesome/3.2.1/css/font-awesome.css", :rel => "stylesheet"}/
    %title= content_for?(:title) ? yield(:title) : "Textbook"
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    = stylesheet_link_tag "application", :media => "all"
    / For third-generation iPad with high-resolution Retina display:
    / Size should be 144 x 144 pixels
    = favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144'
    / For iPhone with high-resolution Retina display:
    / Size should be 114 x 114 pixels
    = favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114'
    / For first- and second-generation iPad:
    / Size should be 72 x 72 pixels
    = favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72'
    / For non-Retina iPhone, iPod Touch, and Android 2.1+ devices:
    / Size should be 57 x 57 pixels
    = favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png'
    / For all other devices
    / Size should be 32 x 32 pixels
    = favicon_link_tag 'favicon.ico', :rel => 'shortcut icon'
    = javascript_include_tag "application"
    :javascript
      function goBack()
      {
        window.history.back()
      }

      $(document).ready(function() {
        $('.link-delete').bind('ajax:beforeSend', function() {
            $('#remove-btn').remove();
            $('#ajax-loader').show();
        });

        $('.link-delete').bind('ajax:complete', function() {
          $('#notification-bar').remove();
        });
      });
  %body
    .navbar.navbar-inverse{:role => "navigation"}
      .navbar-inner
        %a.btn.btn-navbar{"data-target" => ".nav-collapse", "data-toggle" => "collapse"}
          %span.icon-bar
          %span.icon-bar
          %span.icon-bar
        %a.brand{:href => "/"} CWRU Textbook Exchange
        .nav-collapse.collapse
          %ul.nav
            %li= link_to "Find Books", "/search"
            %li= link_to "Sell Books", "/books"
            %li
              = link_to "/messages" do
                Conversations
                - if current_user && !current_user.notifications.blank?
                  %span.badge.badge-important= current_user.notifications.count
          %ul.nav.pull-right
            - if current_user
              %li.dropdown
                %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
                  = current_user.email
                  %b.caret
                %ul.dropdown-menu
                  %li= link_to 'Edit Settings', edit_user_path(current_user.id)
                  %li= link_to 'Sign out', sign_out_path, method: :delete
            - else
              %li= link_to 'Sign in', sign_in_path
    .container
      - if current_user && !current_user.notifications.blank?
        #notification-bar.alert.alert-error{:style => "text-align:center;"}
          %strong
            = current_user.notifications.count
            unread messages!
          = link_to destroy_notifications_path, :remote => true, :class => "link-delete" do
            %i#remove-btn.pull-right.icon-remove{:style => "color: #b94a48;"}
            = image_tag "ajax-loading.gif", :class => "pull-right hide", :id => "ajax-loader"
      = bootstrap_flash
      = yield
    / /row